"""LeadHunter UI polish layer over the working dashboard_v6 router."""
import dashboard_v6 as _base

CSS = r'''
.appearance{position:relative}.appearance-toggle{min-height:42px;padding:8px 11px;border:1.5px solid var(--line);border-radius:12px;background:var(--surface);color:var(--text);font-weight:850;display:inline-flex;align-items:center;gap:7px;cursor:pointer}.appearance-menu{position:absolute;right:0;top:48px;z-index:100;display:none;width:270px;padding:10px;border:1.5px solid var(--line);border-radius:16px;background:var(--surface);box-shadow:6px 7px 0 var(--shadow)}.appearance.open .appearance-menu{display:block}.appearance-menu h4{margin:2px 4px 8px;font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:var(--muted)}.theme-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.theme-choice{border:1.5px solid var(--softline);background:var(--surface2);color:var(--text);border-radius:12px;padding:10px 8px;text-align:left;cursor:pointer;font-weight:800}.theme-choice b{display:block;font-size:11px}.theme-choice small{display:block;margin-top:2px;color:var(--muted);font-size:9px}.theme-choice.active{border-color:var(--accent);background:color-mix(in srgb,var(--accent) 13%,var(--surface))}.theme-choice:focus-visible,.appearance-toggle:focus-visible{outline:3px solid var(--accent);outline-offset:2px}
body.theme-dark-modern{--bg:#07111f;--surface:#0d1d30;--surface2:#11263d;--text:#f5f8ff;--muted:#91a7bd;--line:#37516c;--softline:#31475e;--accent:#55d8ff;--green:#2ee59a;--yellow:#ffd45a;--red:#ff687b;--shadow:#020712;background:radial-gradient(900px 500px at 0 0,#40208044,transparent 65%),radial-gradient(700px 500px at 100% 0,#007f9540,transparent 65%),var(--bg)}
body.theme-light-modern{--bg:#f4f0e7;--surface:#fffdf8;--surface2:#eee9df;--text:#17191c;--muted:#68717a;--line:#1c2228;--softline:#c9c2b7;--accent:#6d4aff;--green:#087a4b;--yellow:#9a7200;--red:#b42336;--shadow:#17191c}
body.theme-light-neo{--bg:#efe8d9;--surface:#fffaf0;--surface2:#e5dccb;--text:#171717;--muted:#625d55;--line:#171717;--softline:#8e8579;--accent:#ff5b35;--green:#087a4b;--yellow:#a06c00;--red:#b42336;--shadow:#171717}.theme-light-neo .topbar,.theme-light-neo .metric,.theme-light-neo .workspace,.theme-light-neo .lead,.theme-light-neo .section,.theme-light-neo .appearance-menu{box-shadow:6px 7px 0 var(--shadow)}.theme-light-neo .btn,.theme-light-neo .iconbtn{box-shadow:3px 3px 0 var(--shadow)}
body.theme-dark-neo{--bg:#090b10;--surface:#12161e;--surface2:#1b202a;--text:#f6f7f9;--muted:#9ba5b3;--line:#f0f2f5;--softline:#596575;--accent:#ffcf33;--green:#3ee7a3;--yellow:#ffd45a;--red:#ff6678;--shadow:#000}.theme-dark-neo .topbar,.theme-dark-neo .metric,.theme-dark-neo .workspace,.theme-dark-neo .lead,.theme-dark-neo .section,.theme-dark-neo .appearance-menu{box-shadow:6px 7px 0 #000}.theme-dark-neo .btn,.theme-dark-neo .iconbtn{box-shadow:3px 3px 0 #000}.theme-dark-neo .btn.primary{background:var(--accent);color:#111}
.sales-priority{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:10px 0}.sales-item{border:1.5px solid var(--softline);border-radius:13px;padding:10px;background:var(--surface2);min-height:76px}.sales-item .sales-icon{font-size:18px}.sales-item small{display:block;margin-top:3px;font-size:8px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);font-weight:900}.sales-item strong{display:block;margin-top:2px;font-size:13px;line-height:1.25}.sales-item.google{border-color:#00a9b8}.sales-item.contact{border-color:var(--green)}.sales-item.problem{border-color:var(--red)}.sales-item.opportunity{border-color:var(--accent)}.details .section{position:relative}.details .section h3{font-weight:950}.details .evidence div{border-left:4px solid var(--accent)}.details .telegram{margin-top:9px}.details .links .link{font-weight:800}
@media(max-width:700px){.appearance-menu{position:fixed;right:9px;top:68px;width:min(300px,calc(100vw - 18px))}.sales-priority{grid-template-columns:1fr 1fr;gap:6px}.sales-item{min-height:70px;padding:8px}.top-actions{flex-wrap:wrap}.appearance-toggle{flex:1}.top-actions .btn{flex:1}}
'''

HTML = r'''
<div class="appearance" id="appearance"><button class="appearance-toggle" type="button" onclick="toggleAppearance()" aria-expanded="false">🎨 <span id="appearanceLabel">Dark · Modern</span> ▾</button><div class="appearance-menu" role="dialog" aria-label="Dashboard appearance"><h4>Choose dashboard look</h4><div class="theme-grid"><button class="theme-choice" data-theme="light-modern" onclick="setTheme('light-modern')">☀️ <b>Light · Modern</b><small>Clean premium</small></button><button class="theme-choice active" data-theme="dark-modern" onclick="setTheme('dark-modern')">🌙 <b>Dark · Modern</b><small>Focused &amp; polished</small></button><button class="theme-choice" data-theme="light-neo" onclick="setTheme('light-neo')">🟠 <b>Light · Neo</b><small>Bold &amp; tactile</small></button><button class="theme-choice" data-theme="dark-neo" onclick="setTheme('dark-neo')">⚡ <b>Dark · Neo</b><small>High contrast</small></button></div></div></div>
'''

JS = r'''
<script>
(function(){const labels={'light-modern':'Light · Modern','dark-modern':'Dark · Modern','light-neo':'Light · Neo','dark-neo':'Dark · Neo'};window.toggleAppearance=function(){const x=document.getElementById('appearance');if(!x)return;x.classList.toggle('open');x.querySelector('.appearance-toggle').setAttribute('aria-expanded',x.classList.contains('open'))};window.setTheme=function(t){if(!labels[t])return;document.body.classList.remove('theme-light-modern','theme-dark-modern','theme-light-neo','theme-dark-neo');document.body.classList.add('theme-'+t);const l=document.getElementById('appearanceLabel');if(l)l.textContent=labels[t];document.querySelectorAll('.theme-choice').forEach(x=>x.classList.toggle('active',x.dataset.theme===t));localStorage.setItem('leadhunter-theme',t)};document.addEventListener('DOMContentLoaded',function(){setTheme(localStorage.getItem('leadhunter-theme')||'dark-modern');document.addEventListener('click',function(e){const x=document.getElementById('appearance');if(x&&!x.contains(e.target))x.classList.remove('open')})})})();
(function(){function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function val(t,keys){for(const k of keys){const i=t.toLowerCase().indexOf(k.toLowerCase());if(i>=0){let s=t.slice(i+k.length).replace(/^\s*[:·-]\s*/,'').trim();return s.slice(0,90)}}return 'Not found'}function add(card){if(card.querySelector('.sales-priority'))return;const d=card.querySelector('.details');if(!d)return;const t=(d.textContent||'').replace(/\s+/g,' ').trim();const s=document.createElement('div');s.className='sales-priority';[['google','📍','Google / Local',val(t,['Google Local Position','Google Local'])],['contact','🌐','Website',val(t,['Website'])],['contact','📞','Phone',val(t,['Phone'])],['contact','✉️','Email',val(t,['Email'])]].forEach(x=>{const n=document.createElement('div');n.className='sales-item '+x[0];n.innerHTML='<span class="sales-icon">'+x[1]+'</span><small>'+x[2]+'</small><strong>'+esc(x[3])+'</strong>';s.appendChild(n)});const h=d.querySelector('.hero');if(h)h.after(s);else d.prepend(s)}function scan(){document.querySelectorAll('.lead').forEach(add)}new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',scan)})();
</script>
'''

page=_base.PAGE
page=page.replace('</style>',CSS+'</style>',1)
# v6 uses top-actions; if absent, put picker before the page body content.
if '<div class="top-actions">' in page:
    page=page.replace('<div class="top-actions">','<div class="top-actions"><div class="appearance-slot">'+HTML+'</div>',1)
else:
    page=page.replace('<body>','<body>'+HTML,1)
page=page.replace('</body>',JS+'</body>',1)
_base.PAGE=page
router=_base.router
