create extension if not exists pgcrypto;

create table if not exists businesses (
    id bigint generated by default as identity primary key,
    name text not null,
    industry text,
    city text,
    website text,
    phone text,
    email text,
    source text,
    source_attribution text,
    source_place_id text,
    identity_key text not null unique,
    score integer default 0 check (score between 0 and 100),
    priority text default 'LOW',
    recommended_services text[] default '{}',
    problems text[] default '{}',
    status text default 'NEW',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table businesses add column if not exists source_attribution text;
alter table businesses add column if not exists source_place_id text;
create index if not exists businesses_city_industry_idx on businesses(city, industry);
create index if not exists businesses_priority_score_idx on businesses(priority, score desc);
create index if not exists businesses_status_idx on businesses(status);

create table if not exists research (
    id bigint generated by default as identity primary key,
    business_id bigint not null references businesses(id) on delete cascade,
    research_json jsonb not null default '{}'::jsonb,
    problems text[] default '{}',
    created_at timestamptz default now()
);
create index if not exists research_business_idx on research(business_id, created_at desc);

create table if not exists activities (
    id bigint generated by default as identity primary key,
    business_id bigint not null references businesses(id) on delete cascade,
    action text not null,
    channel text not null,
    notes text,
    created_at timestamptz default now()
);
create index if not exists activities_business_idx on activities(business_id, created_at desc);

create table if not exists telegram_events (
    id bigint generated by default as identity primary key,
    business_id bigint not null references businesses(id) on delete cascade,
    event text not null,
    telegram_message_id bigint,
    created_at timestamptz default now()
);
create index if not exists telegram_events_business_idx on telegram_events(business_id, created_at desc);

create table if not exists followups (
    id bigint generated by default as identity primary key,
    business_id bigint not null references businesses(id) on delete cascade,
    due_at timestamptz not null,
    status text default 'OPEN',
    notes text,
    created_at timestamptz default now(),
    completed_at timestamptz
);
create index if not exists followups_due_idx on followups(status, due_at);

create table if not exists deals (
    id bigint generated by default as identity primary key,
    business_id bigint not null references businesses(id) on delete cascade,
    value numeric(14,2),
    services text[] default '{}',
    stage text not null,
    notes text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    won_at timestamptz,
    lost_at timestamptz
);
create index if not exists deals_business_idx on deals(business_id, created_at desc);
create index if not exists deals_stage_idx on deals(stage);

create table if not exists daily_stats (
    date date primary key,
    leads_found integer default 0,
    qualified integer default 0,
    hot_leads integer default 0,
    calls integer default 0,
    contacted integer default 0,
    replies integer default 0,
    meetings integer default 0,
    proposals integer default 0,
    won integer default 0,
    lost integer default 0
);

create table if not exists jobs (
    id bigint generated by default as identity primary key,
    job_type text not null,
    city text,
    industry text,
    status text default 'QUEUED',
    started_at timestamptz,
    finished_at timestamptz,
    processed integer default 0,
    succeeded integer default 0,
    failed integer default 0,
    error text,
    created_at timestamptz default now()
);
create index if not exists jobs_status_idx on jobs(status, created_at desc);
