DASHBOARD_HTML = r"""
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>LeadHunter</title>
<style>
:root{--bg:#f6f7fb;--card:#fff;--text:#171923;--muted:#697386;--line:#e8eaf0;--accent:#6c5ce7;--good:#16a34a;--warn:#d97706;--bad:#dc2626}
[data-theme="dark"]{--bg:#11131a;--card:#1a1d27;--text:#f4f6fb;--muted:#a2a9b8;--line:#2a2f3d}
[data-theme="neo-light"]{--bg:#e9eef6;--card:#fff;--text:#10131a;--accent:#008cff}
[data-theme="neo-dark"]{--bg:#080b10;--card:#111722;--text:#eff6ff;--accent:#00d4aa;--line:#263140}
*{box-sizing:border-box}body{margin:0;font:14px Inter,system-ui,sans-serif;background:var(--bg);color:var(--text)}
.app{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{padding:18px;border-right:1px solid var(--line);position:sticky;top:0;height:100vh}
.brand{font-size:22px;font-weight:800;margin-bottom:28px}.brand b{color:var(--accent)}.nav button,.top button{border:0;background:transparent;color:var(--text);padding:11px 12px;border-radius:10px;text-align:left;width:100%;cursor:pointer}.nav button:hover,.nav .active{background:var(--card);box-shadow:0 1px 4px #0000000d}
main{padding:22px;max-width:1500px;width:100%;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.top-right{display:flex;gap:8px}.top-right button{width:auto;background:var(--card);border:1px solid var(--line)}
.page{display:none}.page.active{display:block}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.lead{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:16px}.metric{font-size:26px;font-weight:800}.muted{color:var(--muted)}h1{margin:0 0 5px}h3{margin:0 0 10px}
.form{display:grid;grid-template-columns:1fr 1fr 140px auto;gap:10px}.input{padding:13px;border:1px solid var(--line);border-radius:11px;background:var(--card);color:var(--text)}.primary{background:var(--accent)!important;color:white!important;font-weight:700!important}
.dataset{display:flex;align-items:center;justify-content:space-between;margin:12px 0}.pill{padding:5px 9px;border-radius:999px;background:color-mix(in srgb,var(--accent) 12%,transparent);color:var(--accent);font-size:12px;font-weight:700}
.lead{margin:10px 0;padding:0;overflow:hidden}.lead-head{padding:14px;cursor:pointer;display:grid;grid-template-columns:1fr auto;gap:12px}.lead-title{font-size:16px;font-weight:750}.lead-meta{margin-top:6px;color:var(--muted);display:flex;gap:12px;flex-wrap:wrap}.signals{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.sig{font-size:12px;padding:5px 8px;border-radius:8px;background:var(--bg)}.expand{display:none;padding:0 14px 14px;border-top:1px solid var(--line)}.lead.open .expand{display:block}.sections{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:12px}.section{padding:12px;background:var(--bg);border-radius:11px}.section b{display:block;margin-bottom:7px}.actions{display:flex;gap:8px;margin-top:12px}.actions button{padding:9px 11px;border:1px solid var(--line);background:var(--card);color:var(--text);border-radius:9px;cursor:pointer}
.empty{padding:28px;text-align:center;color:var(--muted)}.toast{position:fixed;right:18px;bottom:18px;background:var(--card);border:1px solid var(--line);padding:12px 16px;border-radius:10px;display:none}
.mobile{display:none}
@media(max-width:900px){.app{display:block}.side{display:none}.grid{grid-template-columns:repeat(2,1fr)}.form{grid-template-columns:1fr 1fr}.sections{grid-template-columns:1fr}.mobile{display:flex;position:fixed;bottom:0;left:0;right:0;background:var(--card);border-top:1px solid var(--line);justify-content:space-around;padding:7px;z-index:9}.mobile button{border:0;background:transparent;color:var(--text);font-size:11px}main{padding-bottom:70px}}
@media(max-width:560px){.grid,.form{grid-template-columns:1fr}.top{align-items:flex-start}.lead-head{grid-template-columns:1fr}.top-right button{padding:8px}}
</style></head>
<body><div class="app">
<aside class="side"><div class="brand">Lead<b>Hunter</b></div><div class="nav">
<button class="active" data-page="overview">⌂ Overview</button><button data-page="find">🔍 Find Leads</button><button data-page="explore">◈ Explore</button><button data-page="analytics">📊 Analytics</button><button data-page="outreach">📤 Outreach</button>
</div></aside>
<main><header class="top"><div><h1 id="title">Overview</h1><div class="muted">Local business intelligence</div></div><div class="top-right"><button onclick="cycleTheme()">🎨 Theme</button><button onclick="showSettings()">⚙️ Settings</button></div></header>
<section id="overview" class="page active"><div class="grid" id="metrics"></div><div class="card" style="margin-top:14px"><h3>Recent activity</h3><div id="recent" class="empty">No activity yet.</div></div></section>
<section id="find" class="page"><div class="card"><h3>Find businesses</h3><div class="form"><input id="category" class="input" placeholder="Business type e.g. Dentist"><input id="city" class="input" placeholder="City e.g. Jabalpur"><input id="limit" class="input" type="number" value="20"><button class="primary" onclick="discover()">🔍 Find Leads</button></div></div><div id="discoverResult"></div></section>
<section id="explore" class="page"><div class="card dataset"><div><b id="datasetTitle">Your leads</b><div class="muted">Compact cards — click to expand intelligence</div></div><button class="primary" style="padding:10px;border:0;border-radius:9px" onclick="loadLeads()">Refresh</button></div><div id="leads"></div></section>
<section id="analytics" class="page"><div class="card"><h3>Analytics</h3><div class="empty">Analytics will populate from real lead and research data.</div></div></section>
<section id="outreach" class="page"><div class="grid"><div class="card"><h3>Ready</h3><div class="metric">0</div><div class="muted">Qualified leads ready for outreach</div></div><div class="card"><h3>Pitch Generated</h3><div class="metric">0</div><div class="muted">Awaiting review</div></div><div class="card"><h3>Sent</h3><div class="metric">0</div><div class="muted">Active outreach</div></div><div class="card"><h3>Follow-up</h3><div class="metric">0</div><div class="muted">Needs attention</div></div></div></section>
</main></div>
<nav class="mobile"><button data-page="overview">⌂<br>Overview</button><button data-page="find">🔍<br>Find</button><button data-page="explore">◈<br>Explore</button><button data-page="analytics">📊<br>Analytics</button><button data-page="outreach">📤<br>Outreach</button></nav>
<div id="toast" class="toast"></div>
<script>
const pages={overview:"Overview",find:"Find Leads",explore:"Explore",analytics:"Analytics",outreach:"Outreach"};
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>go(b.dataset.page));
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(p).classList.add("active");document.getElementById("title").textContent=pages[p];document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="explore")loadLeads()}
function toast(t){let e=document.getElementById("toast");e.textContent=t;e.style.display="block";setTimeout(()=>e.style.display="none",2600)}
let themes=["light","dark","neo-light","neo-dark"],ti=0;function cycleTheme(){ti=(ti+1)%themes.length;document.documentElement.dataset.theme=themes[ti];localStorage.theme=themes[ti];toast("Theme: "+themes[ti])}
function showSettings(){toast("⚙️ Settings: provider and account settings stay in the main app.")}
async function get(url){let r=await fetch("/api"+url);return r.json()}
async function post(url,data){let r=await fetch("/api"+url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});return r.json()}
async function loadOverview(){try{let d=await get("/overview"),m=d.metrics||{};document.getElementById("metrics").innerHTML=[["📁 Datasets",m.datasets||0],["🏢 Leads",m.leads||0],["🔎 Researched",m.researched||0],["📤 Ready",m.ready||0]].map(x=>`<div class="card"><div class="muted">${x[0]}</div><div class="metric">${x[1]}</div></div>`).join("")}catch(e){toast("Overview unavailable")}}
async function discover(){let category=document.getElementById("category").value.trim(),city=document.getElementById("city").value.trim();if(!category||!city)return toast("Enter business type and city");let box=document.getElementById("discoverResult");box.innerHTML='<div class="card" style="margin-top:14px">🔎 Searching…</div>';try{let d=await post("/discover",{category,city,max_results:+document.getElementById("limit").value||20});box.innerHTML='<div class="card" style="margin-top:14px">✅ Discovery completed. Open Explore to view saved results.</div>';toast("Discovery completed")}catch(e){box.innerHTML='<div class="card" style="margin-top:14px">⚠️ Discovery service unavailable. Check backend wiring.</div>'}}
function val(x,...keys){for(let k of keys){if(x&&x[k]!=null)return x[k]}return null}
function leadCard(x,i){let name=val(x,"name","business_name")||"Unnamed Business",city=val(x,"city","location")||"Unknown location",rating=val(x,"rating","google_rating"),reviews=val(x,"review_count","reviews_count"),phone=val(x,"phone"),email=val(x,"email"),site=val(x,"website","url"),address=val(x,"address"),id=val(x,"id","lead_id")||i,score=val(x,"score","opportunity_score");return `<article class="lead"><div class="lead-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="lead-title">🏢 ${esc(name)}</div><div class="lead-meta"><span>${rating?"⭐ "+rating:"⭐ Google unavailable"}</span><span>${reviews?"💬 "+reviews+" reviews":""}</span><span>📍 ${esc(city)}</span></div><div class="signals"><span class="sig">🌐 ${site?"Website found":"Website missing"}</span><span class="sig">🗺️ Google intelligence</span><span class="sig">🎯 ${score??"—"} opportunity</span></div></div><div>⌄</div></div><div class="expand"><div class="sections"><div class="section"><b>📞 CONTACT</b>Phone: ${esc(phone||"—")}<br>Email: ${esc(email||"—")}<br>🌐 ${site?`<a href="${esc(site)}" target="_blank">Website</a>`:"Missing"}<br>📍 ${esc(address||city)}</div><div class="section"><b>🗺️ GOOGLE INTELLIGENCE</b>Profile, Maps visibility and review intelligence appear here when real Research Worker data is available.</div><div class="section"><b>🎯 OPPORTUNITIES</b><div class="signals"><span class="sig">SEO</span><span class="sig">GBP</span><span class="sig">Website</span><span class="sig">Automation</span></div></div></div><div class="actions"><button onclick="event.stopPropagation();action('${id}','research')">🔎 Research</button><button onclick="event.stopPropagation();action('${id}','pitch')">✨ Generate Pitch</button><button onclick="event.stopPropagation();toast('📤 Outreach workflow will use the saved lead')">📤 Outreach</button></div></div></article>`}
function esc(v){return String(v??"").replace(/[&<>"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[s]))}
async function loadLeads(){let box=document.getElementById("leads");box.innerHTML='<div class="empty">Loading leads…</div>';try{let d=await get("/leads"),a=Array.isArray(d.items)?d.items:(Array.isArray(d)?d:[]);box.innerHTML=a.length?a.map(leadCard).join(""):'<div class="card empty">No leads yet. Use Find Leads to create a business dataset.</div>'}catch(e){box.innerHTML='<div class="card empty">Lead data unavailable.</div>'}}
async function action(id,type){toast(type==="research"?"🔎 Research started…":"✨ Generating pitch…");try{let d=await post(`/leads/${id}/${type}`);toast(d.ok?"✅ Completed":"⚠️ Service unavailable");if(type==="research")loadLeads()}catch(e){toast("⚠️ Backend action unavailable")}}
if(localStorage.theme){document.documentElement.dataset.theme=localStorage.theme;ti=Math.max(0,themes.indexOf(localStorage.theme))}loadOverview();
</script></body></html>
"""