DASHBOARD_HTML=r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LeadHunter</title><style>
:root{--bg:#f6f7fb;--card:#fff;--text:#171923;--muted:#697386;--line:#e8eaf0;--accent:#6c5ce7}[data-theme=dark]{--bg:#11131a;--card:#1a1d27;--text:#f4f6fb;--muted:#a2a9b8;--line:#2a2f3d}[data-theme=neo-light]{--bg:#e9eef6;--card:#fff;--text:#10131a;--accent:#008cff}[data-theme=neo-dark]{--bg:#080b10;--card:#111722;--text:#eff6ff;--accent:#00d4aa;--line:#263140}*{box-sizing:border-box}body{margin:0;font:14px system-ui;background:var(--bg);color:var(--text)}.app{display:grid;grid-template-columns:230px 1fr;min-height:100vh}.side{padding:20px;border-right:1px solid var(--line)}.brand{font-size:22px;font-weight:800;margin-bottom:25px}.brand b{color:var(--accent)}button,input{font:inherit}.nav button,.action{width:100%;border:0;background:transparent;color:var(--text);padding:11px;border-radius:10px;text-align:left;cursor:pointer}.nav button:hover,.nav button.active{background:var(--card)}main{padding:24px;max-width:1500px;width:100%;margin:auto}.top{display:flex;justify-content:space-between}.top button,.primary{border:1px solid var(--line);background:var(--card);color:var(--text);padding:10px;border-radius:9px;cursor:pointer}.primary{background:var(--accent);color:#fff;border:0}.page{display:none}.page.active{display:block}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card,.lead{background:var(--card);border:1px solid var(--line);border-radius:15px;padding:15px;margin-top:14px}.metric{font-size:28px;font-weight:800}.muted{color:var(--muted)}.form{display:grid;grid-template-columns:1fr 1fr 110px auto;gap:9px}.input{padding:12px;border:1px solid var(--line);background:var(--card);color:var(--text);border-radius:9px}.dataset{cursor:pointer;display:flex;justify-content:space-between}.lead{padding:0;overflow:hidden}.leadhead{padding:14px;cursor:pointer}.leadbody{display:none;padding:14px;border-top:1px solid var(--line)}.lead.open .leadbody{display:block}.tags{display:flex;gap:6px;flex-wrap:wrap}.tag{padding:5px 8px;background:var(--bg);border-radius:8px;font-size:12px}.row{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.toast{position:fixed;right:20px;bottom:20px;background:var(--card);border:1px solid var(--line);padding:12px;border-radius:9px;display:none}.settings{position:fixed;right:24px;top:70px;width:260px;background:var(--card);border:1px solid var(--line);border-radius:14px;padding:14px;box-shadow:0 12px 40px #0002;display:none;z-index:10}.settings.show{display:block}.settings button{width:100%;margin-top:8px;text-align:center}@media(max-width:800px){.app{display:block}.side{display:none}.grid,.row,.form{grid-template-columns:1fr}main{padding:14px}}
</style></head><body><div class="app"><aside class="side"><div class="brand">Lead<b>Hunter</b><div class="muted" style="font-size:11px;margin-top:4px">v4.1.0 · Research Contract</div></div><div class="nav"><button class="active" data-p="overview">🏠 Overview</button><button data-p="find">🔍 Find Leads</button><button data-p="explore">◈ Explore</button><button data-p="analytics">📊 Analytics</button><button data-p="outreach">📤 Outreach</button></div></aside><main><header class="top"><div><h1 id="title">Overview</h1><div class="muted">Local business intelligence</div></div><div><button onclick="theme()">🎨 Theme</button><button onclick="settings()">⚙️ Settings</button></div></header>
<section id="overview" class="page active"><div class="grid" id="metrics"></div><div class="card"><h3>📁 Recent Datasets</h3><div id="recent"></div></div></section>
<section id="find" class="page"><div class="card"><h3>🔍 Find Businesses</h3><div class="form"><input id="cat" class="input" placeholder="Business type e.g. Dentist"><input id="city" class="input" placeholder="City e.g. Jabalpur"><input id="lim" class="input" type="number" value="20"><button class="primary" onclick="discover()">Find Leads</button></div><div id="progress" class="muted"></div></div></section>
<section id="explore" class="page"><div id="datasets"></div><div id="leads"></div></section>
<section id="analytics" class="page"><div class="grid" id="analyticsCards"></div><div class="card" id="analyticsDetails"></div></section>
<section id="outreach" class="page"><div class="grid" id="outreachCards"></div><div class="card" id="outreachList"></div></section>
</main></div><div id="settingsPanel" class="settings"><b>⚙️ Settings</b><p class="muted">LeadHunter v4.1.0</p><button onclick="theme()">🎨 Change Theme</button></div><div id="toast" class="toast"></div><script>
const $=id=>document.getElementById(id);
const titleEl=$("title"),metricsEl=$("metrics"),recentEl=$("recent"),datasetsEl=$("datasets"),leadsEl=$("leads"),progressEl=$("progress"),analyticsCardsEl=$("analyticsCards"),analyticsDetailsEl=$("analyticsDetails"),outreachCardsEl=$("outreachCards"),outreachListEl=$("outreachList"),catEl=$("cat"),cityEl=$("city"),limEl=$("lim");
let currentDataset=null,themes=["","dark","neo-light","neo-dark"],ti=themes.indexOf(localStorage.leadhunterTheme||"");if(ti<0)ti=0;
async function api(url,opt={}){try{let r=await fetch("/api"+url,{...opt,headers:{...(opt.headers||{})}});let body=await r.text();if(!r.ok)throw Error(body.slice(0,300)||("HTTP "+r.status));return body?JSON.parse(body):{ok:true}}catch(e){console.error("LeadHunter API",url,e);toast("⚠️ API error: "+url+" — "+e.message);throw e}}
function toast(x){let e=document.getElementById("toast");e.textContent=x;e.style.display="block";setTimeout(()=>e.style.display="none",2500)}
function theme(){ti=(ti+1)%themes.length;document.documentElement.dataset.theme=themes[ti];localStorage.leadhunterTheme=themes[ti]}document.documentElement.dataset.theme=localStorage.leadhunterTheme||"";
function settings(){document.getElementById("settingsPanel").classList.toggle("show")}
const names={overview:"Overview",find:"Find Leads",explore:"Explore",analytics:"Analytics",outreach:"Outreach"};document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>go(b.dataset.p));
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(p).classList.add("active");titleEl.textContent=names[p];document.querySelectorAll("[data-p]").forEach(x=>x.classList.toggle("active",x.dataset.p===p));if(p==="overview")loadOverview();if(p==="explore")loadDatasets();if(p==="analytics")loadAnalytics();if(p==="outreach")loadOutreach()}
async function loadOverview(){let d=await api("/overview"),m=d.metrics;metricsEl.innerHTML=[["📁 Datasets",m.datasets],["🔍 Leads",m.leads],["🔬 Researched",m.researched],["🎯 Qualified",m.ready]].map(x=>'<div class="card"><b>'+x[0]+'</b><div class="metric">'+x[1]+'</div></div>').join("");recentEl.innerHTML=d.recent.length?d.recent.map(datasetHTML).join(""):"<p class=muted>No datasets yet.</p>"}
function datasetHTML(x){return '<div class="card dataset" onclick="selectDataset('+x.id+')"><div><b>📁 '+esc(x.industry||"Businesses")+' · '+esc(x.city||"")+'</b><div class=muted>'+x.result_count+' businesses · '+esc(x.status||"")+'</div></div><span>Explore →</span></div>'}
async function loadDatasets(){let d=await api("/datasets");datasetsEl.innerHTML='<h3>EXPLORE DATASETS</h3>'+(d.items.length?d.items.map(datasetHTML).join(""):"<div class=card>No datasets yet.</div>");leadsEl.innerHTML=""}
async function selectDataset(id){currentDataset=id;let d=await api("/datasets/"+id+"/leads");leads.innerHTML='<h3>LEADS</h3>'+(d.items.length?d.items.map(leadHTML).join(""):"<div class=card>No leads in this dataset.</div>")}
function leadHTML(x){let id=x.id||x.business_id,ops=x.recommended_services||[],probs=x.problems||[];return '<div class=lead id="lead'+id+'"><div class=leadhead onclick="document.getElementById(\'lead'+id+'\').classList.toggle(\'open\')"><b>🏢 '+esc(x.name||"Unknown")+'</b><div class=muted>⭐ '+(x.rating??x.google_rating??"—")+' · 💬 '+(x.review_count??x.google_review_count??"—")+' · '+esc(x.industry||"")+' · '+esc(x.city||"")+'</div><div class=tags><span class=tag>📞 '+esc(x.phone||"Missing")+'</span><span class=tag>🌐 '+(x.website?"Website":"No website")+'</span></div></div><div class=leadbody><div class=row><div><b>CONTACT</b><p>📞 '+esc(x.phone||"Unavailable")+'<br>✉️ '+esc(x.email||"Unavailable")+'<br>🌐 '+esc(x.website||"Unavailable")+'<br>📍 '+esc(x.address||"Unavailable")+'</p></div><div><b>GOOGLE</b><p>⭐ '+(x.rating??x.google_rating??"Unavailable")+'<br>💬 '+(x.review_count??x.google_review_count??"Unavailable")+'<br>📍 '+(x.maps_url||x.google_maps_url?'<a href="'+esc(x.maps_url||x.google_maps_url)+'" target=_blank>Open Profile</a>':"Unavailable")+'</p></div><div><b>OPPORTUNITIES</b><div class=tags>'+ops.map(o=>'<span class=tag>🎯 '+esc(o)+'</span>').join("")+(probs.length?probs.map(o=>'<span class=tag>⚠️ '+esc(o)+'</span>').join(""):"<span class=muted>Run research for verified intelligence</span>")+'</div></div></div><div id="intel'+id+'" class=card style="display:none"></div><p><button onclick="research('+id+')">🔎 Research</button> <button onclick="pitch('+id+')">✨ Generate Pitch</button> <button onclick="outreach('+id+')">📤 Outreach</button></p><div id="result'+id+'"></div></div></div>'}
function state(m,label){m=m||{};let s=m.status||"NOT_CONFIGURED",icon=s==="AVAILABLE"?"🟢":s==="NOT_FOUND"?"❌":s==="FAILED"?"⚠️":"⚪";let detail=s==="AVAILABLE"?"Available":s==="NOT_FOUND"?(m.message||"Does not exist / not found"):s==="FAILED"?(m.message||"Check failed"):(m.message||"Data source not connected yet");return '<div class=tag>'+icon+' '+label+': '+esc(detail)+'</div>'}
function renderResearch(id,r,score){let e=document.getElementById("intel"+id);e.style.display="block";let mods=[["website","🌐 Website"],["google","⭐ Google Business"],["reviews","💬 Reviews"],["search","🔍 Search Intelligence"],["organic_ranking","📈 Organic Ranking"],["maps","📍 Maps Ranking"],["competitors","👥 Competitors"],["keywords","🔑 Keywords"],["social","📱 Social"]];e.innerHTML='<b>🧠 RESEARCH INTELLIGENCE</b><div class=tags>'+mods.map(([k,l])=>state(r[k],l)).join("")+'</div><p><b>Score:</b> '+esc(score?.score??"—")+' · '+esc(score?.priority??"")+'</p>'+(r.problems?.length?'<p><b>⚠️ Verified findings</b><br>'+r.problems.map(esc).join("<br>")+'</p>':"")+'<p class=muted>Contract v'+esc(r.meta?.contract_version||"—")+' · Missing sources are shown as NOT CONFIGURED, not as business failures.</p>'}
async function discover(){let category=catEl.value.trim(),cityv=cityEl.value.trim();if(!category||!cityv)return toast("Enter business type and city");let d=await api("/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,city:cityv,max_results:+limEl.value})});if(d.status==="DONE"){toast("Existing dataset opened");selectDataset(d.dataset_id);go("explore");return}progressEl.textContent="🔎 Discovery started…";let t=setInterval(async()=>{let j=await api("/jobs/"+d.job_id);progress.textContent="⏳ "+j.item.status+" · "+j.businesses_found+" businesses";if(["DONE","FAILED"].includes(j.item.status)){clearInterval(t);toast(j.item.status==="DONE"?"✅ Discovery completed":"⚠️ Discovery failed");if(j.item.status==="DONE"){selectDataset(d.job_id);go("explore")}}},2500)}
async function research(id){let e=document.getElementById("result"+id);e.textContent="🔬 Researching…";try{let d=await api("/leads/"+id+"/research",{method:"POST"});renderResearch(id,d.research,d.score);e.textContent="✅ Research updated"}catch(e){toast("Research failed")}}
async function pitch(id){let e=document.getElementById("result"+id);e.textContent="✨ Generating pitch…";try{let d=await api("/leads/"+id+"/pitch",{method:"POST"});e.innerHTML="<b>✨ GENERATED PITCH</b><p>"+esc(d.pitch)+"</p>"}catch(e){toast("Pitch generation failed")}}
async function outreach(id){await api("/outreach/"+id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stage:"READY"})});toast("Added to outreach")}
async function loadAnalytics(){let d=await api("/analytics"),t=d.totals||{};analyticsCardsEl.innerHTML=Object.entries(t).map(([k,v])=>'<div class=card><b>'+esc(k.toUpperCase())+'</b><div class=metric>'+v+'</div></div>').join("");analyticsDetailsEl.innerHTML="<h3>Top Cities</h3>"+(d.cities||[]).map(x=>esc(x.name)+" · "+x.count).join("<br>")+"<h3>Top Industries</h3>"+(d.industries||[]).map(x=>esc(x.name)+" · "+x.count).join("<br>")+"<h3>Top Opportunities</h3>"+(d.services||[]).map(x=>esc(x.name)+" · "+x.count).join("<br>")}
async function loadOutreach(){let d=await api("/outreach"),c=d.counts||{};outreachCardsEl.innerHTML=["READY","PITCH_GENERATED","CONTACTED","FOLLOW_UP"].map(k=>'<div class=card><b>'+k.replace("_"," ")+'</b><div class=metric>'+(c[k]||0)+'</div></div>').join("");outreachListEl.innerHTML="<h3>Pipeline</h3>"+(d.items||[]).map(x=>"<p>📤 <b>"+esc(x.business_name)+"</b> · "+esc(x.stage)+"</p>").join("")+(d.followups||[]).map(x=>"<p>⏰ Follow-up: "+esc(x.business_name)+"</p>").join("")}
function esc(x){let d=document.createElement("div");d.textContent=String(x??"");return d.innerHTML}
loadOverview().catch(e=>console.error("Initial dashboard load failed",e))
</script></body></html>"""